version: '3.8'

services:
  upcensus-db:
    container_name: ${DB_NAME}
    image: ${POSTGRES_VERSION}
    restart: always
    ports:
        - "${LOCAL_DB_PORT}:5432"
    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PWD}
    volumes:
        - ./postgres/upcensus-data:/var/lib/postgresql/data
    
  upcensus:
        container_name: ${UPCENSUS_NAME}
        restart: always
        image: ${JAVA_VERSION}
        ports:
            - "${LOCAL_UPCENSUS_PORT}:8080"
        command: sh -c "java -jar -Xms2048m -Xmx3072m /services/*.jar"
        env_file:
            - .env
        environment:
            DB_HOSTNAME: ${DB_NAME}
            SPRING_PROFILES_ACTIVE: ${ACTIVE_PROFILE}
        volumes:
            - ./target/:/services
        links:
            - upcensus-db
            
            