spring:
  sql:
    init:
      platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}/upcensus
    username: ${DB_USER}
    password: ${DB_PWD}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  flyway:
    baselineOnMigrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <your-client-id>
            clientSecret: <your-client-secret>

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
    oauth2:
      authorizedRedirectUris: http://localhost:8081/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect


server:
  servlet:
    contextPath: /api
  port: ${PORT:8080}
  

cors:
  allowedOrigins:
    - http://localhost:4200
  allowCredentials: true
  
logging:
  runtimeException: true