spring:
  sql:
    init:
      platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}/upcensus
    username: ${DB_USER}
    password: ${DB_PWD}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  flyway:
    baselineOnMigrate: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  servlet:
    contextPath: /api
  port: ${PORT:8080}
  

cors:
  allowedOrigins:
    - http://localhost:4200
  allowCredentials: true
  allowedHeaders:
    - Authorization
    - Content-Type
  
logging:
  runtimeException: true