spring:
  sql:
    init:
      platform: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}/upcensus
    username: ${DB_USER}#postgres
    password: ${DB_PWD}#123456
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  flyway:
    baselineOnMigrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 188652981902-3nn5bcm7m7ndfv9sfj63tsrh7u895u5o.apps.googleusercontent.com
            clientSecret: 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

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
    oauth2:
      authorizedRedirectUris: http://localhost:4200/oauth2/redirect,myandroidapp://oauth2/redirect,myiosapp://oauth2/redirect


server:
  servlet:
    contextPath: /api
  port: ${PORT:8080}
  

cors:
  allowedOrigins:
    - http://localhost:4200
  allowCredentials: true
  
logging:
  runtimeException: true