spring:
  sql:
    init:
      platform: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:5432/upcensus
    username: ${DB_USER}
    password: ${DB_PWD}
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
    
server:
  servlet:
    contextPath: /api